version: 2

jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --no-cache ca-certificates
      - run:
          echo "abc" > '/tmp/a b c'
      - save_cache:
          key: foo
          paths:
            - /tmp
