version: 2

jobs:
  build:
    docker:
      - image: alpine:latest
    environment:
      FOO: "2018-12-31"
    steps:
      - run:
          echo "abc" > '/tmp/a b c'
      - save_cache:
          key: foo
          paths:
            - "/tmp/a b c"
