version: 2

jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - type: artifacts-store
        path: /tmp/foo
      - type: artifacts_store
        path: /tmp/foo
      - type: store_artifacts
        path: /tmp/foo
      - type: store-artifacts
        path: /tmp/foo
      - artifacts-store:
          path: /tmp/foo
      - artifacts_store:
          path: /tmp/foo
      - store_artifacts:
          path: /tmp/foo
      - store-artifacts:
          path: /tmp/foo

workflows:
  version: 2
  test:
    jobs:
      - build
