version: 2

jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run:
          command: "echo 'can i do this?'"
          no_output_timeout: 10

workflows:
  version: 2
  test:
    jobs:
      - build
