version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
    - run: apk add --no-cache ca-certificates
    - save_cache:
        paths: /users/circleci/project folder andsomeotherthing
        key: aiosdjioasdjfoiasjoifjoadj
workflows:
  version: 2
  workflow:
    jobs:
    - build
