version: 2

jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - persist_to_workspace:
          path: package
          root: serverless_build

workflows:
  version: 2
  test:
    jobs:
      - build
