version: 2

jobs:
  build:
    machine:
      enabled: true
      services:
        - docker
    steps:
      - type: store-test-results
        path: /tmp/foo
      - store-test-results:
          path: /tmp/foo
      - type: store_test-results
        path: /tmp/foo
      - store_test-results:
          path: /tmp/foo
      - type: store-test_results
        path: /tmp/foo
      - store-test_results:
          path: /tmp/foo
      - type: store_test_results
        path: /tmp/foo
      - store_test_results:
          path: /tmp/foo
      - type: test-results-store
        path: /tmp/foo
      - test-results-store:
          path: /tmp/foo
      - type: test_results-store
        path: /tmp/foo
      - test_results-store:
          path: /tmp/foo
      - type: test-results_store
        path: /tmp/foo
      - test-results_store:
          path: /tmp/foo
      - type: test_results_store
        path: /tmp/foo
      - test_results_store:
          path: /tmp/foo

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            tags:
              only: /^foo.+/
