version: 2.1
jobs:
  other:
    docker:
      - image: ubuntu:latest
    steps:
      - run: "i am in other job"

  build:
    parameters:
      foo:
        type: string
    docker:
      - image: ubuntu:latest
    steps:
      - run: "echo env: $FOO param: << parameters.foo >>"

workflows:
  workflow:
    jobs:
      - build:
          foo: from-workflow

