version: 2

jobs:
  build:
    machine:
      enabled: true
      working_directory: /tmp
    steps:
      - run: echo hellooooooo
      - run: pwd

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            tags:
              only: /^foo.+/
