version: 2

jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run:
          command: "sleep 11 && echo hi"
          no_output_timeout: 10.5

workflows:
  version: 2
  test:
    jobs:
      - build
