version: 2.1

jobs:
  deploy-lint:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: foobar
  build:
    docker:
      - image: alpine:latest
    steps:
      - run: echo built
  deploy:
    docker:
      - image: alpine:latest
    steps:
      - run: echo deployed
      - run:
          name: bah
      - run:
          name: bah


workflows:
  version: 2
  deploy-production:
    jobs:
      - deploy-lint
      - build
      - deploy:
          requires:
            - build

