version: 2

jobs:
  build:
    docker:
      - image: alpine:latest
    environment:
      FOO: 2018-12-31
    steps:
      - run: echo $FOO

workflows:
  version: 2
  workflow:
    jobs:
      - build
