version: 2

jobs:
  build:
    docker:
      image: ubuntu
      command: []
    steps:
      - run: echo hello

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            tags:
              only: /^foo.+/
