version: '2.1'
jobs:
  "this is the first one-1":
    docker:
    - image: ubuntu:latest
    steps:
    - run:
        command: echo 1
    - run:
        command: echo default
    - run:
        command: echo hello world
  "this is the first one-2":
    docker:
    - image: ubuntu:latest
    steps:
    - run:
        command: echo 1
    - run:
        command: echo default
    - run:
        command: echo hello world
  job-a-1:
    docker:
    - image: ubuntu:latest
    steps:
    - run:
        command: echo hello world
  job-a:
    docker:
    - image: ubuntu:latest
    steps:
    - run:
        command: echo 2
    - run:
        command: echo round 2
    - run:
        command: echo still round 2
    - run:
        command: echo hello world
  named-job:
    docker:
    - image: ubuntu:latest
    steps:
    - run:
        command: echo 3
    - run:
        command: echo round 3
    - run:
        command: echo hello world
workflows:
  version: 2
  foo:
    jobs:
    - this is the first one.-1:
        name: this is the first one.-1 (renamed from this is the first one.)
    - this is the first one.-2:
        name: this is the first one.-2 (renamed from this is the first one.)
    - job-a-1
    - job-a
    - named-job
