version: 2.1

orbs:
  foo:
    jobs:
      test:
        docker:
          - image: "ubuntu:latest"
        steps:
          - run: "echo test"
      build:
        docker:
          - image: "ubuntu:latest"
        steps:
          - run: "echo build"
      deploy:
        docker:
          - image: "ubuntu:latest"
        steps:
          - run: "echo deploy"

workflows:
  version: 2
  main:
    jobs:
      - foo/test:
          filters:
            branches:
              only: master
