version: 2

jobs:
  test:
    docker:
      image: ubuntu
    steps:
      - run: echo hello

  build:
    docker:
      image: ubuntu
    steps:
      - restore_cache: ~
      - run: echo hello

workflows:
  version: 2
  test:
    jobs:
      - test

