version: 2

jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - save_cache:
          paths: .git
      - persist_to_workspace:
          paths: .git
      - run: "echo 'can i do this?'"

workflows:
  version: 2
  test:
    jobs:
      - build
