version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
    - run: apk add --no-cache ca-certificates
    - save_cache:
        paths: /u/c/a b c
        key: aiosdjifoasdjfoiasjoifjoaadja
