version: "2.1"

workflows:
  version: 2
  foo:
    jobs:
    - job-a-1:
        name: job-a-1 (renamed from job-a)
    - job-a-2:
        name: job-a-2 (renamed from job-a)
    - named-job

jobs:
  job-a-1:
    docker:
    - image: ubuntu:latest
    steps:
    - run:
        command: echo 1
    - run:
        command: echo default
    - run:
        command: echo hello world
  job-a-2:
    docker:
    - image: ubuntu:latest
    steps:
    - run:
        command: echo 2
    - run:
        command: echo round 2
    - run:
        command: echo still round 2
    - run:
        command: echo hello world
  named-job:
    docker:
    - image: ubuntu:latest
    steps:
    - run:
        command: echo 3
    - run:
        command: echo round 3
    - run:
        command: echo hello world
