version: "2.1"

jobs:
  test:
    docker:
      - image: "ubuntu:latest"
    steps:
      - run: "echo test"
  build:
    docker:
      - image: "ubuntu:latest"
    steps:
      - run: "echo build"
  deploy:
    docker:
      - image: "ubuntu:latest"
    steps:
      - run: "echo deploy"

workflows:
  main:
    jobs:
      - test
      - build
      - hold:
          type: approval
          requires:
            - test
            - build
      - deploy:
          requires:
            - hold

