version: 2

jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - name: testing
        command: echo oh noes

workflows:
  version: 2
  test:
    jobs:
      - build
