version: 2

jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - artifacts-store:
          path: /tmp/foo

workflows:
  version: 2
  test:
    jobs:
      - build
