version: 2

jobs:
  build:
    docker:
      - image: ubuntu
    macos:
      xcode: '9.0'
    steps:
      run: echo hellooooooo

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            tags:
              only: /^foo.+/
