version: 2

jobs:
  deploy-lint:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: foobar
  build:
    docker:
      - image: alpine:latest
    steps:
      - run: echo built
      - run:
          name: foobar
  deploy:
    docker:
      - image: alpine:latest
    steps:
      - run: echo deployed

workflows:
  version: 2
  deploy-production:
    jobs:
      - build
      - deploy:
          requires:
            - build

