version: 2

jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - run: |
          echo "foo" > project.clj
          echo "abc" > '/tmp/a b c'
      - save_cache:
          key: foo-{{ checksum "project.clj" }}
          paths:
            - /tmp
